import type { ServerDefinition } from "../config/schema.js";
import { LANGUAGE_IDS } from "./language-ids.js";

function ids(extensions: string[]): Record<string, string> {
  return Object.fromEntries(extensions.map((extension) => [extension, LANGUAGE_IDS[extension] ?? extension.slice(1)]));
}
function server(input: Omit<ServerDefinition, "enabled" | "role" | "priority"> & Partial<Pick<ServerDefinition, "enabled" | "role" | "priority">>): ServerDefinition {
  return { enabled: true, role: "primary", priority: 50, ...input };
}

export const BUILTIN_SERVERS: Record<string, ServerDefinition> = Object.fromEntries([
  server({ id: "typescript", displayName: "TypeScript Language Server", command: ["typescript-language-server", "--stdio"], extensions: [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"], languageIds: ids([".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"]), rootMarkers: ["tsconfig.json", "jsconfig.json", "package.json", ".git"], rootFallback: "workspace", priority: 60, diagnosticPolicy: { pushFirstMs: 3_000, settleMs: 100, acceptUnversionedEmptyAfterOpen: true }, installationHint: "npm install -g typescript-language-server typescript" }),
  server({ id: "deno", displayName: "Deno Language Server", command: ["deno", "lsp"], extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs"], languageIds: ids([".ts", ".tsx", ".js", ".jsx", ".mjs"]), rootMarkers: ["deno.json", "deno.jsonc"], rootFallback: "none", priority: 80, initializationOptions: { enable: true }, installationHint: "Install Deno from https://deno.com/" }),
  server({ id: "vue", displayName: "Vue Language Server", command: ["vue-language-server", "--stdio"], extensions: [".vue"], languageIds: { ".vue": "vue" }, rootMarkers: ["vite.config.ts", "vue.config.js", "package.json", "tsconfig.json"], rootFallback: "workspace", installationHint: "npm install -g @vue/language-server" }),
  server({ id: "svelte", displayName: "Svelte Language Server", command: ["svelteserver", "--stdio"], extensions: [".svelte"], languageIds: { ".svelte": "svelte" }, rootMarkers: ["svelte.config.js", "svelte.config.ts", "package.json", "tsconfig.json"], rootFallback: "workspace", installationHint: "npm install -g svelte-language-server" }),
  server({ id: "basedpyright", displayName: "BasedPyright", command: ["basedpyright-langserver", "--stdio"], extensions: [".py", ".pyi"], languageIds: { ".py": "python", ".pyi": "python" }, rootMarkers: ["pyproject.toml", "pyrightconfig.json", "setup.py", "setup.cfg", "requirements.txt", ".git"], rootFallback: "workspace", priority: 70, installationHint: "pipx install basedpyright" }),
  server({ id: "pyright", displayName: "Pyright", command: ["pyright-langserver", "--stdio"], extensions: [".py", ".pyi"], languageIds: { ".py": "python", ".pyi": "python" }, rootMarkers: ["pyproject.toml", "pyrightconfig.json", "setup.py", "setup.cfg", "requirements.txt", ".git"], rootFallback: "workspace", priority: 60, installationHint: "npm install -g pyright" }),
  server({ id: "ruff", displayName: "Ruff Language Server", command: ["ruff", "server"], extensions: [".py", ".pyi"], languageIds: { ".py": "python", ".pyi": "python" }, rootMarkers: ["pyproject.toml", "ruff.toml", ".ruff.toml", ".git"], rootFallback: "workspace", role: "diagnostic", installationHint: "uv tool install ruff" }),
  server({ id: "rust-analyzer", displayName: "rust-analyzer", command: ["rust-analyzer"], extensions: [".rs"], languageIds: ids([".rs"]), rootMarkers: ["Cargo.toml", "Cargo.lock"], rootFallback: "none", installationHint: "rustup component add rust-analyzer" }),
  server({ id: "gopls", displayName: "gopls", command: ["gopls"], extensions: [".go"], languageIds: ids([".go"]), rootMarkers: ["go.work", "go.mod", ".git"], rootFallback: "workspace", installationHint: "go install golang.org/x/tools/gopls@latest" }),
  server({ id: "clangd", displayName: "clangd", command: ["clangd", "--background-index"], extensions: [".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".m", ".mm"], languageIds: { ...ids([".c", ".h", ".cc", ".cpp", ".cxx", ".hpp"]), ".m": "objective-c", ".mm": "objective-cpp" }, rootMarkers: ["compile_commands.json", ".clangd", "CMakeLists.txt", "meson.build", ".git"], rootFallback: "workspace", priority: 65, installationHint: "Install clangd from your system package manager" }),
  server({ id: "jdtls", displayName: "Eclipse JDT Language Server", command: ["jdtls"], extensions: [".java"], languageIds: ids([".java"]), rootMarkers: ["pom.xml", "build.gradle", "build.gradle.kts", ".classpath", ".project"], rootFallback: "none", installationHint: "Install a jdtls wrapper that assigns a unique writable -data directory per workspace" }),
  server({ id: "kotlin", displayName: "Kotlin LSP", command: ["kotlin-lsp"], extensions: [".kt", ".kts"], languageIds: { ".kt": "kotlin", ".kts": "kotlin" }, rootMarkers: ["settings.gradle", "settings.gradle.kts", "build.gradle", "build.gradle.kts", "pom.xml"], rootFallback: "none", installationHint: "Install JetBrains kotlin-lsp" }),
  server({ id: "csharp-ls", displayName: "C# Language Server", command: ["csharp-ls"], extensions: [".cs"], languageIds: ids([".cs"]), rootMarkers: [{ glob: "*.sln" }, { glob: "*.slnx" }, { glob: "*.csproj" }, "global.json"], rootFallback: "none", installationHint: "dotnet tool install --global csharp-ls" }),
  server({ id: "fsautocomplete", displayName: "FsAutoComplete", command: ["fsautocomplete", "--adaptive-lsp-server-enabled"], extensions: [".fs", ".fsi", ".fsx"], languageIds: { ".fs": "fsharp", ".fsi": "fsharp", ".fsx": "fsharp" }, rootMarkers: [{ glob: "*.sln" }, { glob: "*.fsproj" }], rootFallback: "none", installationHint: "dotnet tool install --global fsautocomplete" }),
  server({ id: "sourcekit-lsp", displayName: "SourceKit-LSP", command: ["sourcekit-lsp"], extensions: [".swift"], languageIds: ids([".swift"]), rootMarkers: ["Package.swift", { glob: "*.xcodeproj" }, { glob: "*.xcworkspace" }], rootFallback: "none", installationHint: "Install the Swift toolchain" }),
  server({ id: "ruby-lsp", displayName: "Ruby LSP", command: ["ruby-lsp"], extensions: [".rb", ".rake", ".gemspec"], filenames: ["Gemfile", "Rakefile"], languageIds: { ".rb": "ruby", ".rake": "ruby", ".gemspec": "ruby", Gemfile: "ruby", Rakefile: "ruby" }, rootMarkers: ["Gemfile", ".ruby-version", { glob: "*.gemspec" }], rootFallback: "workspace", installationHint: "gem install ruby-lsp" }),
  server({ id: "intelephense", displayName: "Intelephense", command: ["intelephense", "--stdio"], extensions: [".php"], languageIds: ids([".php"]), rootMarkers: ["composer.json", ".git"], rootFallback: "workspace", installationHint: "npm install -g intelephense" }),
  server({ id: "lua-language-server", displayName: "Lua Language Server", command: ["lua-language-server"], extensions: [".lua"], languageIds: ids([".lua"]), rootMarkers: [".luarc.json", ".luarc.jsonc", ".git"], rootFallback: "workspace", installationHint: "Install lua-language-server" }),
  server({ id: "elixirls", displayName: "ElixirLS", command: ["elixir-ls"], extensions: [".ex", ".exs"], languageIds: ids([".ex", ".exs"]), rootMarkers: ["mix.exs"], rootFallback: "none", installationHint: "Install ElixirLS and expose elixir-ls" }),
  server({ id: "zls", displayName: "ZLS", command: ["zls"], extensions: [".zig"], languageIds: ids([".zig"]), rootMarkers: ["build.zig", "build.zig.zon"], rootFallback: "workspace", installationHint: "Install zls" }),
  server({ id: "dart", displayName: "Dart Analysis Server", command: ["dart", "language-server"], extensions: [".dart"], languageIds: ids([".dart"]), rootMarkers: ["pubspec.yaml"], rootFallback: "none", installationHint: "Install the Dart SDK" }),
  server({ id: "ocamllsp", displayName: "OCaml LSP", command: ["ocamllsp"], extensions: [".ml", ".mli"], languageIds: ids([".ml", ".mli"]), rootMarkers: ["dune-project", "dune-workspace", { glob: "*.opam" }], rootFallback: "none", installationHint: "opam install ocaml-lsp-server" }),
  server({ id: "hls", displayName: "Haskell Language Server", command: ["haskell-language-server-wrapper", "--lsp"], extensions: [".hs", ".lhs"], languageIds: { ".hs": "haskell", ".lhs": "haskell" }, rootMarkers: ["hie.yaml", "cabal.project", "stack.yaml", { glob: "*.cabal" }], rootFallback: "none", installationHint: "Install haskell-language-server" }),
  server({ id: "bash-language-server", displayName: "Bash Language Server", command: ["bash-language-server", "start"], extensions: [".sh", ".bash"], filenames: [".bashrc", ".bash_profile"], languageIds: { ...ids([".sh", ".bash"]), ".bashrc": "shellscript", ".bash_profile": "shellscript" }, rootMarkers: [".git"], rootFallback: "workspace", installationHint: "npm install -g bash-language-server" }),
  server({ id: "clojure-lsp", displayName: "Clojure LSP", command: ["clojure-lsp", "listen"], extensions: [".clj", ".cljs", ".cljc", ".edn"], languageIds: { ".clj": "clojure", ".cljs": "clojure", ".cljc": "clojure", ".edn": "edn" }, rootMarkers: ["deps.edn", "project.clj", "bb.edn"], rootFallback: "none", installationHint: "Install clojure-lsp" }),
  server({ id: "gleam", displayName: "Gleam LSP", command: ["gleam", "lsp"], extensions: [".gleam"], languageIds: ids([".gleam"]), rootMarkers: ["gleam.toml"], rootFallback: "none", installationHint: "Install Gleam" }),
  server({ id: "nixd", displayName: "nixd", command: ["nixd"], extensions: [".nix"], languageIds: ids([".nix"]), rootMarkers: ["flake.nix", "shell.nix", ".git"], rootFallback: "workspace", installationHint: "Install nixd" }),
  server({ id: "terraform-ls", displayName: "Terraform Language Server", command: ["terraform-ls", "serve"], extensions: [".tf", ".tfvars"], languageIds: { ".tf": "terraform", ".tfvars": "terraform-vars" }, rootMarkers: [".terraform.lock.hcl", ".terraform"], rootFallback: "workspace", installationHint: "Install terraform-ls" }),
  server({ id: "yaml", displayName: "YAML Language Server", command: ["yaml-language-server", "--stdio"], extensions: [".yaml", ".yml"], languageIds: ids([".yaml", ".yml"]), rootMarkers: [".yamllint", ".git"], rootFallback: "workspace", installationHint: "npm install -g yaml-language-server" }),
  server({ id: "json", displayName: "JSON Language Server", command: ["vscode-json-language-server", "--stdio"], extensions: [".json", ".jsonc"], languageIds: { ".json": "json", ".jsonc": "jsonc" }, rootMarkers: ["package.json", ".git"], rootFallback: "workspace", installationHint: "npm install -g vscode-langservers-extracted" }),
  server({ id: "html", displayName: "HTML Language Server", command: ["vscode-html-language-server", "--stdio"], extensions: [".html", ".htm"], languageIds: { ".html": "html", ".htm": "html" }, rootMarkers: ["package.json", ".git"], rootFallback: "workspace", installationHint: "npm install -g vscode-langservers-extracted" }),
  server({ id: "css", displayName: "CSS Language Server", command: ["vscode-css-language-server", "--stdio"], extensions: [".css", ".scss", ".less"], languageIds: { ".css": "css", ".scss": "scss", ".less": "less" }, rootMarkers: ["package.json", ".git"], rootFallback: "workspace", installationHint: "npm install -g vscode-langservers-extracted" }),
  server({ id: "prisma", displayName: "Prisma Language Server", command: ["prisma-language-server", "--stdio"], extensions: [".prisma"], languageIds: ids([".prisma"]), rootMarkers: ["schema.prisma", "package.json"], rootFallback: "workspace", installationHint: "npm install -g @prisma/language-server" }),
].map((definition) => [definition.id, definition]));
